### ISSUE TITLE
multitenant support

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/secrets-store-csi-driver-provider-vault#48] opened 2020-08-27 16:54 UTC
if I understand correctly, this csi driver uses the service account in which the csi-secrets-store controller is running to authenticate to vault using the kubernetes authentication method.
This means that all of the secrets will be retrieved with the same account regardless of which namespace the csi secret volume it defined. 
This does not play well  in a multi-tenant environment in which each namespace is assigned to a different tenant and each tenant needs to be strictly isolated.
Can you confirm that this is the case? If this is the case, are there workarounds to this problem?
Ideally the controller should use the a service account from the namespace in which the csi driver is defined. the service account to use should be passed as a parameter, if not passed it should default to the default service account.

**Comment by joshrosso** [comment] 2020-09-01 00:41
Funny, I was digging into this today and was checking to see if an issue was filed :laughing:.

This is the case and I believe the primary limitation is and upstream issue around the service-account needing to be propagated down to the csi-driver. 

You can read about it in issue https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/issues/16, which I believe this can be closed in favor of.

**Comment by mitsutaka** [comment] 2020-09-02 14:22
Since there is not much activity, I was wondering if a PR should be prepared.

I use it like this: First, specify `NodePublishSecretRef` in the CSI entry of the pod, and use the Service Account token to access the vault. `NodePublishVolumeRequest` of secrets-store-csi-driver is already implemented to receive this token, and token JWT is passed to provider's `--secrets` [flag](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/d8fd297972a9eb674c3102f6bad97e0f98d5104e/pkg/secrets-store/nodeserver.go#L328
).

However, this is not the case with the current master branch implementation of the vault-provider.

The current implementation of master branch either specifies `vaultKubernetesServiceAccountPath` on the `SecretProviderClass` or else uses the token from secrets-store-csi-driver DaemonSet. Therefore, it can be said that it is not supported as a multitenant.

https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/master/provider.go#L418-L421

I customize and use it. Specifically, I do not use `vaultKubernetesServiceAccountPath` or default csi-driver's token, and pass it to JWT of Kubernetes Auth method using `--secrets` value of vault-provider. Furthermore, the Kubernetes Auth method receives [metadata](https://www.vaultproject.io/api-docs/auth/kubernetes#sample-response-3) in an entity when returning token, so we can define [Templated ACL](https://learn.hashicorp.com/tutorials/vault/policy-templating) using this. In this way, access control for each namespace is realized by combining one vault policy and Kubernetes Auth method role. for example

```
path "secrets/data/{{identity.entity.aliases.auth_kubernetes_xxxxxxxx.metadata.service_account_namespace}}/*" {
  capabilities = [ "read" ]
}
```

Hope it helps. And I will make PR if you're interested in it.

This is just one method, and I think that which token to use depends on the implementation how secrets-store-csi-driver selects Token JWT. csi-driver would also able to read from particular service account by itself. In my case, it is implemented without customizing csi-drvier because csi-drvier is implemented so that JWT can be read from `NodePublishVolumeRequest` as described above. Incidentally, `vaultKubernetesServiceAccountPath` is not a useful parameter because the current implementation must specify the path that can be read from the csi-driver DaemonSet.

**Comment by tomhjp** [comment] 2021-01-28 16:29
Thanks for raising this, as mentioned in the comments, this is a dupe of #16. It's definitely on our radar to fix this!

**Closed** 2021-01-28 16:29 UTC
